SupplyProject/Models/PedidoFinal_usuario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoFinal_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoFinal_usuario()
        {
            this.EnvioFornecedor = new HashSet<EnvioFornecedor>();
        }
    
        public int idPedido { get; set; }
        public int Usuario_idUsuario { get; set; }
        public int Produto_fornecedor_idProduto_fornecedor { get; set; }
        public int Armazem_idArmazem { get; set; }
        public int statusPedido { get; set; }
        public double preco_pedido { get; set; }
        public int ano_pedido { get; set; }
        public int mes_pedido { get; set; }
        public int dia_pedido { get; set; }
        public int quantidade { get; set; }
        public Nullable<int> Avaliar { get; set; }
    
        public virtual Armazem Armazem { get; set; }
        public virtual Produto_fornecedor Produto_fornecedor { get; set; }
        public virtual StatusPedido StatusPedido1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvioFornecedor> EnvioFornecedor { get; set; }
    }
}

SupplyProject/Controllers/PedidoFinalUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using Remotion.Linq.Parsing.ExpressionVisitors.TreeEvaluation;
using SupplyProject.Models;
using SupplyProject.Services;

namespace SupplyProject.Controllers
{
    public class PedidoFinalUsuarioController : BaseController
    {
        private SupplyProject_dbEntities db = new SupplyProject_dbEntities();

        // GET: PedidoFinalUsuario
        public ActionResult Index()
        {
            var pedidoFinal_usuario = db.PedidoFinal_usuario.Include(p => p.Armazem).Include(p => p.Produto_fornecedor).Include(p => p.StatusPedido1).Where(p => p.statusPedido == 1).Include(p => p.Usuario).Include(p => p.EnvioFornecedor);

            return View(pedidoFinal_usuario.ToList());
        }

        public ActionResult ConfirmarPedido()
        {
            return View();
        }

        public ActionResult IndexEncerrado()
        {
            var pedidoFinal_usuario = db.PedidoFinal_usuario.Include(p => p.Armazem).Include(p => p.Produto_fornecedor).Include(p => p.StatusPedido1).Where(p => p.statusPedido == 2).Include(p => p.Usuario);
            return View(pedidoFinal_usuario.ToList());
        }
        public ActionResult ExibirEstatisticas()
        {
            return View();
        }

        public ActionResult ExibirPedidoPorRegiao()
        {
            return View();
        }


        // GET: PedidoFinalUsuario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoFinal_usuario pedidoFinal_usuario = db.PedidoFinal_usuario.Find(id);
            if (pedidoFinal_usuario == null)
            {
                return HttpNotFound();
            }

            //dados fornecedor
            Produto_fornecedor prodForn= db.Produto_fornecedor.Find(pedidoFinal_usuario.Produto_fornecedor_idProduto_fornecedor);
            Fornecedor fornecedor = db.Fornecedor.Find(prodForn.Fornecedor_idFornecedor);
            String cepForn = fornecedor.CEP;

            //dados armazem
            Produto_armazem prodArm = db.Produto_armazem.Find(prodForn.idProduto_fornecedor);
            Armazem armazem = db.Armazem.Find(prodArm.Armazem_idArmazem);
            String cepArmazem = armazem.CEP;

            //carrega o xml
            CalculaFreteController calculaFrete = new CalculaFreteController();
            XElement xml = calculaFrete.CalculaDistancia(cepForn, cepArmazem);
            // Formatar a resposta
            /*
            String valores = string.Format("Origem: {0} \n Destino: {1} \n Duração da Viagem: {2} \n Distância: {3}",
                //Pegar endereço de origem
                xml.Element("origin_address").Value,
                //Pegar endereço de destino
                xml.Element("destination_address").Value,
                //Pegar duração
                xml.Element("row").Element("element").Element("duration").Element("text").Value,
                //Pegar distância ente os dois pontos
                xml.Element("row").Element("element").Element("distance").Element("text").Value
                );*/
            String origem = string.Format("Origem: {0}", xml.Element("origin_address").Value);
            String destino = string.Format("Destino: {0}", xml.Element("destination_address").Value);
            String distancia = string.Format("Distancia: {0}", xml.Element("row").Element("element").Element("distance").Element("text").Value);
            String duracao = string.Format("Duração Estimada da viajem: {0}", xml.Element("row").Element("element").Element("duration").Element("text").Value);
            String valores = origem + "\n" + destino + "\n" + distancia + "\n" + duracao;

            ViewBag.DadosFrete = valores;

            return View(pedidoFinal_usuario);
        }

        public ActionResult DetailsEncerrado(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoFinal_usuario pedidoFinal_usuario = db.PedidoFinal_usuario.Find(id);
            if (pedidoFinal_usuario == null)
            {
                return HttpNotFound();
            }

            EnvioFornecedor envioFornecedor = db.EnvioFornecedor.Where(t => t.idPedido == pedidoFinal_usuario.idPedido).FirstOrDefault();

            //dados fornecedor
            Produto_fornecedor prodForn = db.Produto_fornecedor.Find(pedidoFinal_usuario.Produto_fornecedor_idProduto_fornecedor);
            Fornecedor fornecedor = db.Fornecedor.Find(prodForn.Fornecedor_idFornecedor);
            String cepForn = fornecedor.CEP;
            ViewBag.Fornecedor = fornecedor.nome_fornecedor;

            //valor de custo
            Veiculo veiculo = db.Veiculo.Find(envioFornecedor.idVeiculo);
            double.TryParse(veiculo.custo_frete, out double custoPKM);

            //dados armazem
            Produto_armazem prodArm = db.Produto_armazem.Find(prodForn.idProduto_fornecedor);
            Armazem armazem = db.Armazem.Find(prodArm.Armazem_idArmazem);
            String cepArmazem = armazem.CEP;

            //carrega o xml
            CalculaFreteController calculaFrete = new CalculaFreteController();
            XElement xml = calculaFrete.CalculaDistancia(cepForn, cepArmazem);

            String origem = string.Format("Origem: {0}", xml.Element("origin_address").Value);
            String destino = string.Format("Destino: {0}", xml.Element("destination_address").Value);
            String distancia = string.Format("Distancia: {0}", xml.Element("row").Element("element").Element("distance").Element("text").Value);
            String duracao = string.Format("Duração Estimada da viajem: {0}", xml.Element("row").Element("element").Element("duration").Element("text").Value);


            var element = xml.Element("row").Element("element").Element("distance").Element("text").Value;
            var result = System.Text.RegularExpressions.Regex.Split(element," ");

            var distance = result[0];
            double distancaeInt = Convert.ToDouble(distance);

            double Custo = distancaeInt * custoPKM;
            String custoTotal = "Frete: " + Custo.ToString();

            String valores = origem + "\n" + destino + "\n" + distancia + "\n" + duracao + "\n" + custoTotal;

            ViewBag.DadosFrete = valores;

            return View(pedidoFinal_usuario);
        }

        // GET: PedidoFinalUsuario/Create
        public ActionResult Create()
        {
            int id = UsuarioService.VerificaSeOUsuarioEstaLogado().idUsuario;

            ViewBag.Armazem_idArmazem = new SelectList(db.Armazem, "idArmazem", "nome_armazem");
            ViewBag.Produto_fornecedor_idProduto_fornecedor = new SelectList(db.Produto_fornecedor, "idProduto_fornecedor", "nome_prodF");
            ViewBag.statusPedido = new SelectList(db.StatusPedido, "idStatus", "nome_status");
            ViewBag.Usuario_idUsuario = new SelectList(db.Usuario.Where(e => e.idUsuario == id), "idUsuario", "nome_usuario");
            return View();
        }

        // POST: PedidoFinalUsuario/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idPedido,Usuario_idUsuario,Produto_fornecedor_idProduto_fornecedor,ano_pedido,mes_pedido,dia_pedido,quantidade")] PedidoFinal_usuario pedidoFinal_usuario)
        {
            int produtoForn = pedidoFinal_usuario.Produto_fornecedor_idProduto_fornecedor;
            Produto_armazem produtoArm = db.Produto_armazem.Find(produtoForn);
            int armazemFinal = produtoArm.Armazem_idArmazem;

            Produto_fornecedor produtoFornecedor = db.Produto_fornecedor.Find(pedidoFinal_usuario.Produto_fornecedor_idProduto_fornecedor);
            double precoProduto = produtoFornecedor.preco_prodF;
            pedidoFinal_usuario.preco_pedido = precoProduto * pedidoFinal_usuario. quantidade;
            pedidoFinal_usuario.Armazem_idArmazem = armazemFinal;
            pedidoFinal_usuario.statusPedido = 1;


            if (ModelState.IsValid)
            {
                db.PedidoFinal_usuario.Add(pedidoFinal_usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            ViewBag.Armazem_idArmazem = new SelectList(db.Armazem, "idArmazem", "nome_armazem", pedidoFinal_usuario.Armazem_idArmazem);
            ViewBag.Produto_fornecedor_idProduto_fornecedor = new SelectList(db.Produto_fornecedor, "idProduto_fornecedor", "nome_prodF", pedidoFinal_usuario.Produto_fornecedor_idProduto_fornecedor);
            ViewBag.statusPedido = new SelectList(db.StatusPedido, "idStatus", "nome_status", pedidoFinal_usuario.statusPedido);
            ViewBag.Usuario_idUsuario = new SelectList(db.Usuario, "idUsuario", "nome_usuario", pedidoFinal_usuario.Usuario_idUsuario);

            return View(pedidoFinal_usuario);
            
        }

        // GET: PedidoFinalUsuario/VizualizarNFe/5
        public ActionResult VizualizarNFe(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoFinal_usuario pedido = db.PedidoFinal_usuario.Find(id);
            if(pedido == null)
            {
                return HttpNotFound();
            }

             Produto_fornecedor produto = db.Produto_fornecedor.Find(pedido.Produto_fornecedor_idProduto_fornecedor);

SupplyProject/Views/PedidoFinalUsuario/ConfirmarPedido.cshtml
@model SupplyProject.Models.PedidoFinal_usuario
@{
    ViewBag.Title = "ConfirmarPedido";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ConfirmarPedido</h2>

<div>
    <h4>Pedido do usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Id pedido
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idPedido)
        </dd>

        <dt>
            Id, Nome usuario
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario_idUsuario), @Html.DisplayFor(model => model.Usuario.nome_usuario)
        </dd>

        <dt>
            Armazem destino
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Armazem.nome_armazem)
        </dd>

        <dt>
            Item pedido
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Produto_fornecedor.nome_prodF)
        </dd>

        <dt>
            quantidade
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantidade)
        </dd>

        <dt>
            Valor do pedido
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preco_pedido)
        </dd>

        <dt>
            Dados de Entrega
        </dt>
        <dd>
            @ViewBag.DadosFrete
        </dd>

        <dt>
            Data de abertura
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dia_pedido)/@Html.DisplayFor(model => model.mes_pedido)/@Html.DisplayFor(model => model.ano_pedido)
        </dd>

    </dl>
</div>

SupplyProject/Views/PedidoFinalUsuario/Create.cshtml
@model SupplyProject.Models.PedidoFinal_usuario

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Gerar Pedido</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Pedido para fornecedor</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Usuario_idUsuario, "Usuario", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Usuario_idUsuario", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Usuario_idUsuario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Produto_fornecedor_idProduto_fornecedor, "Produto", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Produto_fornecedor_idProduto_fornecedor", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Produto_fornecedor_idProduto_fornecedor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.quantidade, "Quantidade", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.quantidade, new { htmlAttributes = new { @class = "form-control" ,@min="0"} })
            @Html.ValidationMessageFor(model => model.quantidade, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Armazem_idArmazem, "Armazem_idArmazem", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Armazem_idArmazem", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Armazem_idArmazem, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.statusPedido, "statusPedido", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("statusPedido", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.statusPedido, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.preco_pedido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.preco_pedido, new { htmlAttributes = new { @class = "form-control" } })
            Html.ValidationMessageFor(model => model.preco_pedido, "", new { @class = "text-danger" })
                @Html.DisplayFor(model => model.preco_pedido)
            </div>
        </div>*@

    <div class="form-group invisible">
        @Html.LabelFor(model => model.ano_pedido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ano_pedido, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.Year } })
            @Html.ValidationMessageFor(model => model.ano_pedido, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enviar" class="btn btn-default" />
        </div>
    </div>
    <div>
        @Html.ActionLink("Cancelar", "Index")
    </div>

    <div class="form-group invisible">
        @Html.LabelFor(model => model.mes_pedido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mes_pedido, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.Month } })
            @Html.ValidationMessageFor(model => model.mes_pedido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group invisible">
        @Html.LabelFor(model => model.dia_pedido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dia_pedido, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.Day } })
            @Html.ValidationMessageFor(model => model.dia_pedido, "", new { @class = "text-danger" })
        </div>
    </div>


</div>
}

SupplyProject/Views/PedidoFinalUsuario/Delete.cshtml
@model SupplyProject.Models.PedidoFinal_usuario

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cancelar</h2>

<h3>Voce tem certeza que quer cancelar esse pedido?</h3>
<div>
    <h4>Pedido para fornecedor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Id pedido
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idPedido)
        </dd>

        <dt>
            Id, Nome usuario
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario_idUsuario), @Html.DisplayFor(model => model.Usuario.nome_usuario)
        </dd>

        <dt>
            Armazem destino
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Armazem.nome_armazem)
        </dd>

        <dt>
            Item pedido
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Produto_fornecedor.nome_prodF)
        </dd>

        <dt>
           quantidade
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantidade)
        </dd>

        <dt>
            Valor do pedido
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preco_pedido)
        </dd>

        <dt>
            Status do pedido
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StatusPedido1.nome_status)
        </dd>

        <dt>
            Data de abertura
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dia_pedido)/@Html.DisplayFor(model => model.mes_pedido)/@Html.DisplayFor(model => model.ano_pedido)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancelar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

SupplyProject/Views/PedidoFinalUsuario/ExibirEstatisticas.cshtml
@{
    ViewBag.Title = "ExibirEstatisticas";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<div class="container-fluid">
    <h2>
        Informações sobre os pedidos: <br />

    </h2>
    <div class="container-fluid">
        <iframe class="ocupacaoFrame" src="https://app.powerbi.com/view?r=eyJrIjoiMGNlZmNkN2MtYjRhMi00OTk5LWI3YjEtODExZWEyYmI2OTk5IiwidCI6ImQ0ZWM1MDg2LTBlY2EtNDQ3Yy04NjE5LTA5ZDY0YzExZTMzZCJ9" frameborder="0" allowFullScreen="true"></iframe>
    </div>
    
</div>
<div class="container-fluid">



</div>
@Html.ActionLink("Voltar para Lista", "IndexEncerrado")

SupplyProject/Views/PedidoFinalUsuario/Index.cshtml
@model IEnumerable<SupplyProject.Models.PedidoFinal_usuario>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Pedidos em aberto</h2>

<table class="table">
    <tr>
        <th>
            Id Pedido
        </th>
        <th>
            Usuario responsavel
        </th>
        <th>
            Status
        </th>
        <th>
            Valor do pedido
        </th>
        <th>
            Data
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idPedido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.nome_usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusPedido1.nome_status)
            </td>
            
            <td>
                @string.Format("{0:C}", item.preco_pedido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dia_pedido)/@Html.DisplayFor(modelItem => item.mes_pedido)/@Html.DisplayFor(modelItem => item.ano_pedido)
            </td>

            <td>
                @*@Html.ActionLink("Concluir", "Edit", new { id=item.idPedido }) |*@
                @if (Session["tipoUsuario"].ToString() == "Gerente" || Session["tipoUsuario"].ToString() == "SupplyChain")
                {
                    @Html.ActionLink("Cancelar", "Delete", new { id = item.idPedido })
                } |
                 @Html.ActionLink("Nota Fiscal", "VizualizarNFe", new { id = item.idPedido }) |


                @Html.ActionLink("Detalhar", "Details", new { id = item.idPedido }) |


            </td>
        </tr>
    }
</table>

@*<input type="hidden" name="name" value="@Url.Action("SalvarAvaliacao", "PedidoFinalUsuario")" />*@

SupplyProject/Views/PedidoFinalUsuario/IndexEncerrado.cshtml
@model IEnumerable<SupplyProject.Models.PedidoFinal_usuario>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Pedidos Encerrados</h2>

<p>
    @Html.ActionLink("Informações sobre pedidos", "ExibirEstatisticas")
</p>
<table class="table">
    <tr>
        <th>
            Id Pedido
        </th>
        <th>
            Usuario responsavel
        </th>
        <th>
            Status
        </th>
        <th>
            Valor do pedido
        </th>
        <th>
            Data
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idPedido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.nome_usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusPedido1.nome_status)
            </td>
            <td>
                @string.Format("{0:C}", item.preco_pedido)
                @*@Html.DisplayFor(modelItem => item.preco_pedido)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dia_pedido)/@Html.DisplayFor(modelItem => item.mes_pedido)/@Html.DisplayFor(modelItem => item.ano_pedido)
            </td>
            <td>

                @Html.ActionLink("Nota Fiscal", "VizualizarNFe", new { id = item.idPedido }) |

                @Html.ActionLink("Detalhar", "DetailsEncerrado", new { id = item.idPedido })
                |
                @if (item.Avaliar != 1)
                {
                    <p data-toggle="modal" data-target="#exampleModal_@item.idPedido">Avaliar</p>

                    <!-- Button trigger modal -->
                    @*<button type="button" class="btn btn-primary">
                        Launch demo modal
                    </button>*@

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal_@item.idPedido" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" style="color: black;" id="exampleModalLabel" color="black">Formulario de Avaliação</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label for="exampleFormControlSelect2" style="color: black;">Nota da Entrega</label>
                                        <select multiple class="form-control" id="formAvaliacao_@item.idPedido">
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                            <option>5</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1" style="color: black;">Avaliação da Entrega</label>
                                        <textarea class="form-control" id="formTexto_@item.idPedido" rows="3"></textarea>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                    <button id="@item.idPedido" type="button" class="enviarNotificao btn btn-primary">Salvar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </td>
        </tr>
    }

</table>

<style>


</style>

<script src="~/Content/Doc/js/jquery-1.11.0.min.js"></script>
<script>
    $(document).ready(function () {
        //var urlApagarNotificacao = $("#urlApagarNotificacao").val();
        $(".enviarNotificao").click(function() {

            var id = this.id;

            var avaliacaoNota = $("#formAvaliacao_" + id).val().toString();
            var avaliacaoTexto = $("#formTexto_" + id).val();
            
            debugger;

            var data = {
                Id: id,
                Nota: avaliacaoNota,
                Texto: avaliacaoTexto
            };

            enviarAvaliacao(data);
        });

        function enviarAvaliacao(data) {
            $.ajax({
                type: "POST",
                data: JSON.stringify(data),
                url: "@Url.Action("SalvarAvaliacao", "PedidoFinalUsuario")",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    if (response > 0) {
                        alert("salvo com sucesso");    
                    }else{
                        alert("Falha ao salvar a avaliação");    
                    }
                    
                    window.location.reload();
                },
                failure: function (response) {
                    alert("Erro no servidor, consulte o suporte.");
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        }
    });
</script>