SupplyProject/Controllers/ProdutosArmazemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SupplyProject.Models;
using SupplyProject.Services;

namespace SupplyProject.Controllers
{
    public class ProdutosArmazemController : BaseController
    {
        private SupplyProject_dbEntities db = new SupplyProject_dbEntities();

        // GET: ProdutosArmazem
        public ActionResult Index()
        {
            var produto_armazem = db.Produto_armazem.Include(p => p.Armazem).Include(p => p.Usuario);
            return View(produto_armazem.ToList());
        }

        public ActionResult ExibirEstatisticas()
        {
            return View();
        }

        // GET: ProdutosArmazem/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto_armazem produto_armazem = db.Produto_armazem.Find(id);
            if (produto_armazem == null)
            {
                return HttpNotFound();
            }
            return View(produto_armazem);
        }

        // GET: ProdutosArmazem/Create
        public ActionResult Create()
        {
            ViewBag.Armazem_idArmazem = new SelectList(db.Armazem, "idArmazem", "nome_armazem");
            ViewBag.Usuario_idUsuario = new SelectList(db.Usuario, "idUsuario", "nome_usuario");
            return View();
        }

        // POST: ProdutosArmazem/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idProduto_armazem,nome_prodA,preco_prodA,peso_prodA,largura_prodA,altura_prodA,profundidade_prodA,quantidade_prodA,Usuario_idUsuario,Armazem_idArmazem")] Produto_armazem produto_armazem)
        {
            if (ModelState.IsValid)
            {
                db.Produto_armazem.Add(produto_armazem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Armazem_idArmazem = new SelectList(db.Armazem, "idArmazem", "nome_armazem", produto_armazem.Armazem_idArmazem);
            ViewBag.Usuario_idUsuario = new SelectList(db.Usuario, "idUsuario", "nome_usuario", produto_armazem.Usuario_idUsuario);
            return View(produto_armazem);
        }

        // GET: ProdutosArmazem/Edit/5
        public ActionResult Atualizar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto_armazem produto_armazem = db.Produto_armazem.Find(id);
            if (produto_armazem == null)
            {
                return HttpNotFound();
            }

     

            ViewBag.Armazem_idArmazem = new SelectList(db.Armazem, "idArmazem", "nome_armazem", produto_armazem.Armazem_idArmazem);
            ViewBag.Usuario_idUsuario = new SelectList(db.Usuario.Where(d => d.tipo_usuario.Equals("Supply")), "idUsuario", "nome_usuario", produto_armazem.Usuario_idUsuario);

            return View(produto_armazem);
        }

        // POST: ProdutosArmazem/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idProduto_armazem,nome_prodA,preco_prodA,peso_prodA,largura_prodA,altura_prodA,profundidade_prodA,quantidade_prodA,Usuario_idUsuario,Armazem_idArmazem")] Produto_armazem produto_armazem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produto_armazem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Armazem_idArmazem = new SelectList(db.Armazem, "idArmazem", "nome_armazem", produto_armazem.Armazem_idArmazem);
            ViewBag.Usuario_idUsuario = new SelectList(db.Usuario, "idUsuario", "nome_usuario", produto_armazem.Usuario_idUsuario);
            return View(produto_armazem);
        }

       public ActionResult AtulizaArmazem(Produto_armazem produto)
        {
            if (ModelState.IsValid)
            {
               db.Entry(produto).State = EntityState.Modified;
               db.SaveChanges();
            }

           return View("IndexEncerrado", "PedidoFinalUsuario");

       }

        // GET: ProdutosArmazem/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto_armazem produto_armazem = db.Produto_armazem.Find(id);
            if (produto_armazem == null)
            {
                return HttpNotFound();
            }
            return View(produto_armazem);
        }

        // POST: ProdutosArmazem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produto_armazem produto_armazem = db.Produto_armazem.Find(id);
            db.Produto_armazem.Remove(produto_armazem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SupplyProject/Views/ProdutosArmazem/Atualizar.cshtml
@model SupplyProject.Models.Produto_armazem

@{
    ViewBag.Title = "Edit";
}

<h2>Atualizar</h2>


@using (Html.BeginForm("Edit", "ProdutosArmazem"))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Produto do armazem</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idProduto_armazem)

    <div class="form-group">
        @Html.LabelFor(model => model.Usuario_idUsuario, "Usuario responsavel", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Usuario_idUsuario", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Usuario_idUsuario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Armazem_idArmazem, "Armazem para estoque", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Armazem_idArmazem", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Armazem_idArmazem, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group invisible">
        @Html.LabelFor(model => model.nome_prodA, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nome_prodA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nome_prodA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Atualizar" class="btn btn-default" />
        </div>
    </div>

    <div>
        @Html.ActionLink("Voltar", "Index")
    </div>

    <div class="form-group invisible">
        @Html.LabelFor(model => model.preco_prodA, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.preco_prodA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.preco_prodA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group invisible">
        @Html.LabelFor(model => model.peso_prodA, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.peso_prodA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.peso_prodA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group invisible">
        @Html.LabelFor(model => model.largura_prodA, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.largura_prodA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.largura_prodA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group invisible">
        @Html.LabelFor(model => model.altura_prodA, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.altura_prodA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.altura_prodA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group invisible">
        @Html.LabelFor(model => model.profundidade_prodA, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.profundidade_prodA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.profundidade_prodA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group invisible">
        @Html.LabelFor(model => model.quantidade_prodA, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.quantidade_prodA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.quantidade_prodA, "", new { @class = "text-danger" })
        </div>
    </div>




</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SupplyProject/Views/ProdutosArmazem/Create.cshtml
@model SupplyProject.Models.Produto_armazem

@{
    ViewBag.Title = "Create";
}

<h2>Criar novo produto</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produto do armazem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nome_prodA,"Nome produto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome_prodA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome_prodA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.preco_prodA,"Preco", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.preco_prodA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.preco_prodA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.peso_prodA,"Peso", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.peso_prodA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.peso_prodA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.largura_prodA,"Largura em cm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.largura_prodA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.largura_prodA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.altura_prodA, "Altura em cm",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.altura_prodA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.altura_prodA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.profundidade_prodA,"Profundidade em cm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profundidade_prodA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profundidade_prodA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantidade_prodA,"Quantidade", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantidade_prodA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantidade_prodA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Usuario_idUsuario, "Usuario Responsavel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Usuario_idUsuario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Usuario_idUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Armazem_idArmazem, "Armazem_idArmazem", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Armazem_idArmazem", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Armazem_idArmazem, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group invisible">
            <label> Espaco</label>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Inserir" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SupplyProject/Views/ProdutosArmazem/Delete.cshtml
@model SupplyProject.Models.Produto_armazem

@{
    ViewBag.Title = "Delete";
}

<h2>Deletar</h2>

<h3>Você tem certeza que quer deletar esse item?</h3>
<div>
    <h4>Produto do Armazem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Produto
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome_prodA)
        </dd>

        <dt>
            Preço
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preco_prodA)
        </dd>

        <dt>
           Peso
        </dt>

        <dd>
            @Html.DisplayFor(model => model.peso_prodA)
        </dd>

        <dt>
            Largura
        </dt>

        <dd>
            @Html.DisplayFor(model => model.largura_prodA)
        </dd>

        <dt>
            Altura
        </dt>

        <dd>
            @Html.DisplayFor(model => model.altura_prodA)
        </dd>

        <dt>
            Profundidade
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profundidade_prodA)
        </dd>

        <dt>
            Quantidade
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantidade_prodA)
        </dd>

        <dt>
            Armazem onde se encontra
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Armazem.nome_armazem)
        </dd>

        <dt>
            Usuario responsável
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario.nome_usuario)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para lista", "Index")
        </div>
    }
</div>

SupplyProject/Views/ProdutosArmazem/Details.cshtml
@model SupplyProject.Models.Produto_armazem

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Produto do armazem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Id Produto
        </dt>
        <dd>
            @Html.DisplayFor(model => model.idProduto_armazem)
        </dd>

        <dt>
              Produto
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nome_prodA)
        </dd>

        <dt>
            Quantidade
        </dt>
        <dd>
            @Html.DisplayFor(model => model.quantidade_prodA)
        </dd>

        <dt>
            Preco
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preco_prodA)
        </dd>

        <dt>
            Peso
        </dt>

        <dd>
            @Html.DisplayFor(model => model.peso_prodA)
        </dd>

        <dt>
            Altura (cm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.altura_prodA)
        </dd>

        <dt>
            Largura (cm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.largura_prodA)
        </dd>

        <dt>
            Profundidade (cm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profundidade_prodA)
        </dd>

        <dt>
            Armazem onde se encontra
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Armazem.nome_armazem)
        </dd>
        <dt>
            Usuario responsavel
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Usuario.nome_usuario)
        </dd>

    </dl>
</div>
<p>
  
    @Html.ActionLink("Voltar", "Index")
</p>

SupplyProject/Views/ProdutosArmazem/ExibirEstatisticas.cshtml
@{
    ViewBag.Title = "ExibirEstatisticas";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}
<div class="container-fluid">
    <h2>
        Estatisticas Avancadas: <br />
        Segue Abaixo alguns gráficos referentes aos produtos do armazem
    </h2>
</div>
<div class="container-fluid">

    <div class="double-container">
        <iframe class="iframe-esquerda" src="https://app.powerbi.com/view?r=eyJrIjoiNWQ3ODg4MTMtNWQwYi00OTMwLTg1YmUtNWQ0ZGY3YWIzODNjIiwidCI6ImQ0ZWM1MDg2LTBlY2EtNDQ3Yy04NjE5LTA5ZDY0YzExZTMzZCJ9" frameborder="0" allowFullScreen="true"></iframe>
        <div class="double-container-right">
            <iframe class="iframe-direita" src="https://app.powerbi.com/view?r=eyJrIjoiMjQ1ODEzNjktODIxZi00ZmM1LThmY2MtMzRjNzkxNDM2ZTM5IiwidCI6ImQ0ZWM1MDg2LTBlY2EtNDQ3Yy04NjE5LTA5ZDY0YzExZTMzZCJ9" frameborder="0" allowFullScreen="true"></iframe>
        </div>
    </div>

    <div class="double-container">
        <iframe class="iframe-esquerda" src="https://app.powerbi.com/view?r=eyJrIjoiYWFmOTRhZWYtMTc2Mi00YTdhLTkxMzEtOTVkNTYxNWY0MzRmIiwidCI6ImQ0ZWM1MDg2LTBlY2EtNDQ3Yy04NjE5LTA5ZDY0YzExZTMzZCJ9" frameborder="0" allowFullScreen="true"></iframe>
        <div class="double-container-right">
            <iframe class="iframe-direita" src="https://app.powerbi.com/view?r=eyJrIjoiNDkzZjAxYTAtMzU1NS00NTBmLWJlZjAtYmFiNmU4MTg3NzcxIiwidCI6ImQ0ZWM1MDg2LTBlY2EtNDQ3Yy04NjE5LTA5ZDY0YzExZTMzZCJ9" frameborder="0" allowFullScreen="true"></iframe>
        </div>
    </div>
    <div class="double-container">
        <iframe class="iframe-esquerda" src="https://app.powerbi.com/view?r=eyJrIjoiNjYxNzZkNmYtNzQ2Yy00ZjgxLWE4NDktZmRiZGQxNDBkMGY1IiwidCI6ImQ0ZWM1MDg2LTBlY2EtNDQ3Yy04NjE5LTA5ZDY0YzExZTMzZCJ9" frameborder="0" allowFullScreen="true"></iframe>
        <div class="double-container-right">
            @*<iframe class="iframe-direita" src="https://app.powerbi.com/view?r=eyJrIjoiNjYxNzZkNmYtNzQ2Yy00ZjgxLWE4NDktZmRiZGQxNDBkMGY1IiwidCI6ImQ0ZWM1MDg2LTBlY2EtNDQ3Yy04NjE5LTA5ZDY0YzExZTMzZCJ9" frameborder="0" allowFullScreen="true"></iframe>*@
        </div>
    </div>


</div>
@Html.ActionLink("Voltar para Lista", "Index")

SupplyProject/Views/ProdutosArmazem/Index.cshtml
@model IEnumerable<SupplyProject.Models.Produto_armazem>

@{
    ViewBag.Title = "Index";
}

@{
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

<h2>Produtos em Estoque</h2>
@if (Session["tipoUsuario"].ToString() == "Gerente" || Session["tipoUsuario"].ToString() == "SupplyChain")
{
    <p>
        @Html.ActionLink("Exibir Gráficos", "ExibirEstatisticas")
    </p>

    @*<p>
        @Html.ActionLink("Inserir novo produto", "Create")
    </p>*@
}

<table class="table">
    <tr>
        <th>
            Id Produto
        </th>
        <th>
            Nome produto
        </th>
        <th>
            Quantidade em estoque
        </th>
        <th>
            Usuario responsavel
        </th>
        <th>
            Armazem onde se encontra
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idProduto_armazem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nome_prodA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantidade_prodA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.nome_usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Armazem.nome_armazem)
            </td>
            <td>
                @if (Session["tipoUsuario"].ToString() == "Gerente")
                {
                    @Html.ActionLink("Atualizar", "Atualizar", new { id = item.idProduto_armazem })
                }
                | @Html.ActionLink("Detalhar", "Details", new { id = item.idProduto_armazem }) |

            </td>
        </tr>
    }

</table>